allowBuilds:
  '@scarf/scarf': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@scarf/scarf'
  - unrs-resolver
onlyBuiltDependencies:
  - esbuild
  - protobufjs
